edited

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -451,31 +451,14 @@ jobs:
             echo $BACKEND
             export API_URL="http://${BACKEND}:3030"
 
-            TRIES=60
-            FAILED=0
-            curl "${API_URL}/api/status" || FAILED=1
-            
-            while [ $FAILED -eq 1 ]
-            do
-              FAILED=0
-              echo "Trying again"
-              sleep 4
-              curl "${API_URL}/api/status" || FAILED=1
-              TRIES=$(( $TRIES - 1 ))
-              
-              if [ $TRIES -eq 0 ]
-              then
-                return 1
-              fi
-            done
 
-
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
+            if curl -s --head "API_URL:3030/api/status"
             then
-              return 0
+              echo "API is running on $API_URL"
+              exit 0
             else
-              return 1
+              echo "API cannot be reached!"
+              exit 1
             fi
 
       - run:
